Migrate engine compatibility from nodejs 6.10 to 8.10
CoorpAcademy/aws-batch-triggering-lambda pull request #2
Opened 2019-04-02 09:52 UTC by arthfael-breanainn

Hello,

AWS sended me this message through the dashboard :
> Invokes for functions configured to run on node.js 6.10 will continue to work normally, however the ability to create new Lambda functions configured to use the node.js 6.10 runtime will be disabled on April 30 2019. Code updates to existing functions using node.js 6.10 will be disabled 30 days later on May 30 2019

The migration should be anticipating. I submit these changes to your review. I hope this will be convenient.

2019-04-03 17:19 UTC, AdrieanKhisbe requested changes
Looks like you kind of mess up with the git history.

I see commit from #1.

Can you try to fix it?
If you prefer I can take care to do it, retrieving your commit and cleaning it from the other changes.
(which ean change wont happen from the PR which will be closed)

2019-04-03 17:19 UTC, AdrieanKhisbe commented on .eslintrc
> +    "ecmaVersion": 8,
2017 would be better I think

2019-04-04 12:03 UTC, arthfael-breanainn commented
I'll try to fix my mistake with the git history.
thx for you review

2019-04-09 13:20 UTC, arthfael-breanainn commented
I tried to fix my mistake with the git history.
Let me know if it's ok for you.

2019-04-09 18:03 UTC, AdrieanKhisbe commented
@arthfael-breanainn There is still the merge commit: https://github.com/CoorpAcademy/aws-batch-triggering-lambda/pull/2/commits/5e6db78701aa3d1e05c4e683a3f5746c3e011f5f.

I would prefer you to rebase interactive and remove it so I can merge or rebase your PR, rather than squash it. 

sorry for the inconvenience :)

2019-04-30 15:12 UTC, AdrieanKhisbe commented
@arthfael-breanainn Gentle reminder 😉

2019-05-06 08:36 UTC, arthfael-breanainn commented
Thank you. I will do changes this week. sorry for the delay.

2019-05-06 08:52 UTC, AdrieanKhisbe commented
@arthfael-breanainn No need, I made the changes: https://github.com/CoorpAcademy/aws-batch-triggering-lambda/commit/70b28226d6154aaac23c178d25e7ae4a68e23cba

Thanks you :)

2019-05-06 08:52 UTC, closed without merging